In [3]:
import torch

path = "burgers_train_16.pt"  # adjust if needed
data = torch.load(path, map_location="cpu")

print(type(data))
print(data.keys() if isinstance(data, dict) else data[:2])


<class 'dict'>
dict_keys(['x', 'y', 'visc'])


In [4]:
print(data.keys())
# e.g. dict_keys(['x', 'y'])
x = data["x"]  # input grid/IC
y = data["y"]  # solution
print(x.shape, y.shape)


dict_keys(['x', 'y', 'visc'])
torch.Size([800, 16]) torch.Size([800, 17, 16])


In [5]:
print(x[0])

tensor([ 0.1509,  0.0968,  0.0171, -0.0663, -0.1373, -0.1715, -0.1542, -0.0999,
        -0.0510, -0.0312, -0.0305, -0.0109,  0.0449,  0.1103,  0.1604,  0.1723],
       dtype=torch.float64)


In [12]:
import torch

c = torch.cat((x[0], x[0][0:1]), dim=0)         # shape [5]
# c = tensor([1, 2, 3, 4, 5])

In [13]:
c

tensor([ 0.1509,  0.0968,  0.0171, -0.0663, -0.1373, -0.1715, -0.1542, -0.0999,
        -0.0510, -0.0312, -0.0305, -0.0109,  0.0449,  0.1103,  0.1604,  0.1723,
         0.1509], dtype=torch.float64)

In [9]:
print(x[1])

tensor([-0.0673,  0.2881,  0.5526,  0.6910,  0.7270,  0.6742,  0.5383,  0.3352,
         0.1055, -0.1263, -0.3662, -0.5996, -0.7751, -0.8302, -0.7130, -0.4337],
       dtype=torch.float64)


In [10]:
print(y[0])

tensor([[ 0.1509,  0.0968,  0.0171, -0.0663, -0.1373, -0.1715, -0.1542, -0.0999,
         -0.0510, -0.0312, -0.0305, -0.0109,  0.0449,  0.1103,  0.1604,  0.1723],
        [ 0.1507,  0.0989,  0.0180, -0.0693, -0.1380, -0.1644, -0.1432, -0.0959,
         -0.0537, -0.0339, -0.0272, -0.0053,  0.0436,  0.1024,  0.1496,  0.1677],
        [ 0.1497,  0.1004,  0.0185, -0.0716, -0.1371, -0.1569, -0.1346, -0.0927,
         -0.0555, -0.0355, -0.0246, -0.0012,  0.0428,  0.0958,  0.1406,  0.1619],
        [ 0.1479,  0.1013,  0.0186, -0.0729, -0.1350, -0.1498, -0.1275, -0.0899,
         -0.0565, -0.0364, -0.0223,  0.0019,  0.0422,  0.0903,  0.1327,  0.1557],
        [ 0.1452,  0.1015,  0.0187, -0.0734, -0.1320, -0.1433, -0.1216, -0.0876,
         -0.0571, -0.0367, -0.0204,  0.0042,  0.0416,  0.0857,  0.1257,  0.1496],
        [ 0.1419,  0.1011,  0.0187, -0.0731, -0.1284, -0.1372, -0.1165, -0.0855,
         -0.0573, -0.0367, -0.0188,  0.0059,  0.0409,  0.0817,  0.1195,  0.1437],
        [ 0.1383,  0.1